substitutions:
  name: esphome-web-e8b868
  friendly_name: HIFI-ESP32-Plus
  task_stack_in_psram: "false"

  # ===== Board-Specific Pinouts =====
  # I2S Audio (PCM5122 DAC)
  i2s_lrclk_pin: GPIO25
  i2s_bclk_pin: GPIO26
  i2s_dout_pin: GPIO22
  
  # I2C pins for DAC control
  i2c_sda_pin: GPIO21               # I2C pins are swapped on the rev J. 
  i2c_scl_pin: GPIO27               # These are correct for Rev J1 and later
  pcm5122_i2c_address: 0x4D         
  pcm5122_enable_pin: GPIO13        # optional, to enable/disable the DAC (XSMT physical pin)

  # RGB LED
  rgb_led_pin: GPIO12
  
  # # IR Receiver
  # ir_rx_pin: GPIO39

  # Ethernet (W5500)
  eth_cs_pin: GPIO05
  eth_interrupt_pin: GPIO35
  eth_reset_pin: GPIO14

  # SPI pins
  spi_clk_pin: GPIO18
  spi_mosi_pin: GPIO23
  spi_miso_pin: GPIO19
  
  # Display control pins
  display_cs_pin: GPIO15
  display_dc_pin: GPIO04
  display_reset_pin: GPIO32

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2025.12.2
  platformio_options:
    board_build.flash_mode: dio

esp32:
  variant: esp32
  flash_size: 8MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    version: recommended
    advanced:
      minimum_chip_revision: "3.1" 
    sdkconfig_options:
      # Moves instructions and read only data from flash into PSRAM on boot.
      # Both enabled allows instructions to execute while a flash operation is in progress without needing to be placed in IRAM.
      # Considerably speeds up mWW at the cost of using more PSRAM.
      CONFIG_SPIRAM_RODATA: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: "y"
      CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"
      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"
      
# Enable logging
logger:
  level: DEBUG

api:

ota:
  platform: esphome
  password: !secret esphome_ota_password

wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password

psram:
  speed: 80MHz

network:
  enable_ipv6: true

external_components:
  # for production, use the released version
  # - source: github://sonocotta/esphome-pcm5122
  # for local development, use relative path
  - source: ../..
    components: [ pcm5122 ]
    refresh: 0s

i2c:
  sda: ${i2c_sda_pin}
  scl: ${i2c_scl_pin}
  frequency: 400kHz
  scan: true

audio_dac:
  - platform: pcm5122
    id: external_dac
    address: ${pcm5122_i2c_address}         # I2C address of the DAC, it is 0x4C n the HiFi-ESP32 Rev H, and 0x4D on the rev H1+
    enable_pin: ${pcm5122_enable_pin}       # optional, to enable/disable the DAC (XSMT pin)
    volume_max: 0dB                         # maximum volume range 0dB, can go up to +24dB
    volume_min: -60dB                       # minimum volume range -60dB, can go down to -103dB
    analog_gain: -6dB                       # or -6Db for 1V RMS output, default is 0dB = 2V RMS output
    mixer_mode: STEREO                      # MIXER MODE: STEREO, STEREO_INVERSE, LEFT, RIGHT

switch:
  - platform: pcm5122
    enable_dac:
      name: Enable DAC
      id: enable_dac
      restore_mode: ALWAYS_OFF

select:
  - platform: pcm5122
    process_flow:
      name: PCM5122 Process Flow
      id: pcm5122_process_flow

# ===== Packages =====
packages:
  esparagus_remote:
    url: https://github.com/sonocotta/esp32-audio-dock
    ref: main
    files:
      - firmware/esphome/packages/audio.yaml
      - firmware/esphome/packages/audio-addon-external-dac.yaml
      - firmware/esphome/packages/media-player.yaml
      - firmware/esphome/packages/media-player-addon-dac-enable.yaml

      - firmware/esphome/packages/light.yaml
      # - firmware/esphome/packages/ir-receiver.yaml
      # - firmware/esphome/packages/monitoring.yaml
      # - firmware/esphome/packages/monitoring-wifi.yaml